version: '3.8'

# Override para produção
# Use com: docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d

services:
  api:
    environment:
      - NODE_ENV=production
    volumes:
      - ./data:/app/data
      # Sem volume de código em produção
    
  web:
    build:
      target: runner  # Use a imagem de produção
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE=https://chat.agentesintegrados.com
      - NEXT_PUBLIC_WS_BASE=wss://chat.agentesintegrados.com
    volumes:
      # Sem volumes de código em produção
      - /app/node_modules
      - /app/.next
    command: node server.js
    
  caddy:
    environment:
      - DOMAIN=chat.agentesintegrados.com
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile.prod:/etc/caddy/Caddyfile
      - caddy-data:/data
      - caddy-config:/config
      - ./ssl:/etc/caddy/ssl  # Para certificados customizados se necessário